CREATE DATABASE IF NOT EXISTS sparring DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE sparring;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    contraseña VARCHAR(255) NOT NULL,
    género VARCHAR(50) NOT NULL,
    experiencia VARCHAR(50) NOT NULL,
    peso DECIMAL(5,2) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
